model ../src/subset_sum.mod;
data ../../instances/ampl_instances/ss_inst_20b_70n.dat;

option solver cplex;
option cplex_options 'timelimit=600';
option cplex_options 'integrality=3e-07';
solve;

display _solve_elapsed_time > ss_inst_20b_70n.out;
display calculated_sum > ss_inst_20b_70n.out;
display target_sum > ss_inst_20b_70n.out;
display set_len > ss_inst_20b_70n.out;
display x > ss_inst_20b_70n.out;

